// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO "categories" (
  user_id,
  name,
  type,
  parent_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, name, type, parent_id, created_at, updated_at
`

type CreateCategoryParams struct {
	UserID   pgtype.UUID
	Name     string
	Type     string
	ParentID pgtype.UUID
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.ParentID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM "categories"
WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, user_id, name, type, parent_id, created_at, updated_at FROM "categories"
WHERE id = $1 AND user_id = $2
`

type GetCategoryParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, user_id, name, type, parent_id, created_at, updated_at FROM "categories"
WHERE user_id = $1 AND parent_id IS NULL
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubCategories = `-- name: ListSubCategories :many
SELECT id, user_id, name, type, parent_id, created_at, updated_at FROM "categories"
WHERE user_id = $1 AND parent_id = $2
ORDER BY name
`

type ListSubCategoriesParams struct {
	UserID   pgtype.UUID
	ParentID pgtype.UUID
}

func (q *Queries) ListSubCategories(ctx context.Context, arg ListSubCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listSubCategories, arg.UserID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE "categories"
SET
  name = $2,
  type = $3,
  parent_id = $4,
  updated_at = now()
WHERE
  id = $1 AND user_id = $5
RETURNING id, user_id, name, type, parent_id, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID       pgtype.UUID
	Name     string
	Type     string
	ParentID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.ParentID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
