// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyExpenseTrend = `-- name: GetDailyExpenseTrend :many
SELECT 
    DATE(transaction_date)::date AS date,
    SUM(amount)::numeric AS total_amount
FROM transactions
WHERE user_id = $1 
  AND type = 'EXPENSE'
  AND transaction_date >= $2 
  AND transaction_date <= $3
  AND deleted_at IS NULL
GROUP BY DATE(transaction_date)
ORDER BY date ASC
`

type GetDailyExpenseTrendParams struct {
	UserID            int64              `json:"user_id"`
	TransactionDate   pgtype.Timestamptz `json:"transaction_date"`
	TransactionDate_2 pgtype.Timestamptz `json:"transaction_date_2"`
}

type GetDailyExpenseTrendRow struct {
	Date        pgtype.Date    `json:"date"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) GetDailyExpenseTrend(ctx context.Context, arg GetDailyExpenseTrendParams) ([]GetDailyExpenseTrendRow, error) {
	rows, err := q.db.Query(ctx, getDailyExpenseTrend, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyExpenseTrendRow{}
	for rows.Next() {
		var i GetDailyExpenseTrendRow
		if err := rows.Scan(&i.Date, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardSummary = `-- name: GetDashboardSummary :one
SELECT 
    COALESCE(SUM(CASE WHEN type = 'INCOME' THEN amount ELSE 0 END), 0)::numeric AS total_income,
    COALESCE(SUM(CASE WHEN type = 'EXPENSE' THEN amount ELSE 0 END), 0)::numeric AS total_expense
FROM transactions
WHERE user_id = $1 
  AND transaction_date >= $2 
  AND transaction_date <= $3
  AND deleted_at IS NULL
`

type GetDashboardSummaryParams struct {
	UserID            int64              `json:"user_id"`
	TransactionDate   pgtype.Timestamptz `json:"transaction_date"`
	TransactionDate_2 pgtype.Timestamptz `json:"transaction_date_2"`
}

type GetDashboardSummaryRow struct {
	TotalIncome  pgtype.Numeric `json:"total_income"`
	TotalExpense pgtype.Numeric `json:"total_expense"`
}

func (q *Queries) GetDashboardSummary(ctx context.Context, arg GetDashboardSummaryParams) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSummary, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	var i GetDashboardSummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const getExpenseByCategory = `-- name: GetExpenseByCategory :many
SELECT 
    c.name AS category_name, 
    c.icon_url,
    SUM(t.amount)::numeric AS total_amount,
    COUNT(t.id) AS transaction_count
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1 
  AND t.type = 'EXPENSE'
  AND t.transaction_date >= $2 
  AND t.transaction_date <= $3
  AND t.deleted_at IS NULL
GROUP BY c.name, c.icon_url
ORDER BY total_amount DESC
LIMIT 5
`

type GetExpenseByCategoryParams struct {
	UserID            int64              `json:"user_id"`
	TransactionDate   pgtype.Timestamptz `json:"transaction_date"`
	TransactionDate_2 pgtype.Timestamptz `json:"transaction_date_2"`
}

type GetExpenseByCategoryRow struct {
	CategoryName     string         `json:"category_name"`
	IconUrl          pgtype.Text    `json:"icon_url"`
	TotalAmount      pgtype.Numeric `json:"total_amount"`
	TransactionCount int64          `json:"transaction_count"`
}

func (q *Queries) GetExpenseByCategory(ctx context.Context, arg GetExpenseByCategoryParams) ([]GetExpenseByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getExpenseByCategory, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpenseByCategoryRow{}
	for rows.Next() {
		var i GetExpenseByCategoryRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.IconUrl,
			&i.TotalAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalBalance = `-- name: GetTotalBalance :one
SELECT 
    (COALESCE(SUM(CASE WHEN type = 'INCOME' THEN amount ELSE 0 END), 0) - 
     COALESCE(SUM(CASE WHEN type = 'EXPENSE' THEN amount ELSE 0 END), 0))::numeric AS current_balance
FROM transactions
WHERE user_id = $1 
  AND deleted_at IS NULL
`

func (q *Queries) GetTotalBalance(ctx context.Context, userID int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalBalance, userID)
	var current_balance pgtype.Numeric
	err := row.Scan(&current_balance)
	return current_balance, err
}
