// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	IconUrl   pgtype.Text        `json:"icon_url"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Description     pgtype.Text        `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	Type            string             `json:"type"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	Name         pgtype.Text        `json:"name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	GoogleAuthID pgtype.Text        `json:"google_auth_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
