// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetCategoriesByUser(ctx context.Context, arg GetCategoriesByUserParams) ([]GetCategoriesByUserRow, error)
	GetCategory(ctx context.Context, id int64) (GetCategoryRow, error)
	GetExpenseByDateRange(ctx context.Context, arg GetExpenseByDateRangeParams) (interface{}, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserBalance(ctx context.Context, userID int64) (int32, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleAuthID(ctx context.Context, googleAuthID pgtype.Text) (User, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
