// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: receipts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO "receipts" (
  transaction_id,
  image_url,
  raw_text
) VALUES (
  $1, $2, $3
)
RETURNING id, transaction_id, image_url, raw_text, created_at
`

type CreateReceiptParams struct {
	TransactionID pgtype.UUID
	ImageUrl      string
	RawText       pgtype.Text
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, createReceipt, arg.TransactionID, arg.ImageUrl, arg.RawText)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ImageUrl,
		&i.RawText,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReceipt = `-- name: DeleteReceipt :exec
DELETE FROM "receipts"
WHERE id = $1
`

func (q *Queries) DeleteReceipt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReceipt, id)
	return err
}

const getReceiptByTransactionID = `-- name: GetReceiptByTransactionID :one
SELECT id, transaction_id, image_url, raw_text, created_at FROM "receipts"
WHERE transaction_id = $1
`

func (q *Queries) GetReceiptByTransactionID(ctx context.Context, transactionID pgtype.UUID) (Receipt, error) {
	row := q.db.QueryRow(ctx, getReceiptByTransactionID, transactionID)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ImageUrl,
		&i.RawText,
		&i.CreatedAt,
	)
	return i, err
}
