// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO "transactions" (
  user_id,
  account_id,
  category_id,
  amount,
  description,
  transaction_date
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, account_id, category_id, amount, description, transaction_date, created_at
`

type CreateTransactionParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Description     string             `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM "transactions"
WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, account_id, category_id, amount, description, transaction_date, created_at FROM "transactions"
WHERE id = $1 AND user_id = $2
`

type GetTransactionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, account_id, category_id, amount, description, transaction_date, created_at FROM "transactions"
WHERE user_id = $1
ORDER BY transaction_date DESC
LIMIT $2
OFFSET $3
`

type ListTransactionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, user_id, account_id, category_id, amount, description, transaction_date, created_at FROM "transactions"
WHERE user_id = $1 AND account_id = $2
ORDER BY transaction_date DESC
LIMIT $3
OFFSET $4
`

type ListTransactionsByAccountParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	AccountID pgtype.UUID `json:"account_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount,
		arg.UserID,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByDateRange = `-- name: ListTransactionsByDateRange :many
SELECT id, user_id, account_id, category_id, amount, description, transaction_date, created_at FROM "transactions"
WHERE
  user_id = $1 AND
  transaction_date >= $2 AND
  transaction_date <= $3
ORDER BY transaction_date DESC
`

type ListTransactionsByDateRangeParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	TransactionDate   pgtype.Timestamptz `json:"transaction_date"`
	TransactionDate_2 pgtype.Timestamptz `json:"transaction_date_2"`
}

func (q *Queries) ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByDateRange, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE "transactions"
SET
  account_id = $2,
  category_id = $3,
  amount = $4,
  description = $5,
  transaction_date = $6
WHERE
  id = $1 AND user_id = $7
RETURNING id, user_id, account_id, category_id, amount, description, transaction_date, created_at
`

type UpdateTransactionParams struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Description     string             `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	UserID          pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.TransactionDate,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedAt,
	)
	return i, err
}
