// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, category_id, amount, description, transaction_date, type
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, category_id, amount, description, transaction_date, type, created_at
`

type CreateTransactionParams struct {
	UserID          int64              `json:"user_id"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Description     pgtype.Text        `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	Type            string             `json:"type"`
}

type CreateTransactionRow struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Description     pgtype.Text        `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	Type            string             `json:"type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.TransactionDate,
		arg.Type,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.TransactionDate,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
UPDATE transactions SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getExpenseByDateRange = `-- name: GetExpenseByDateRange :one
SELECT COALESCE(SUM(amount), 0) as total_expense
FROM transactions
WHERE user_id = $1 
  AND type = 'EXPENSE' 
  AND transaction_date BETWEEN $2 AND $3
  AND deleted_at IS NULL
`

type GetExpenseByDateRangeParams struct {
	UserID            int64              `json:"user_id"`
	TransactionDate   pgtype.Timestamptz `json:"transaction_date"`
	TransactionDate_2 pgtype.Timestamptz `json:"transaction_date_2"`
}

func (q *Queries) GetExpenseByDateRange(ctx context.Context, arg GetExpenseByDateRangeParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getExpenseByDateRange, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	var total_expense interface{}
	err := row.Scan(&total_expense)
	return total_expense, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, category_id, amount, description, transaction_date, type
FROM transactions
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL LIMIT 1
`

type GetTransactionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetTransactionRow struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Description     pgtype.Text        `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	Type            string             `json:"type"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.TransactionDate,
		&i.Type,
	)
	return i, err
}

const getUserBalance = `-- name: GetUserBalance :one
SELECT 
    COALESCE(SUM(CASE WHEN type = 'INCOME' THEN amount ELSE 0 END), 0) - 
    COALESCE(SUM(CASE WHEN type = 'EXPENSE' THEN amount ELSE 0 END), 0) 
    AS current_balance
FROM transactions
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserBalance(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getUserBalance, userID)
	var current_balance int32
	err := row.Scan(&current_balance)
	return current_balance, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, category_id, amount, description, transaction_date, type
FROM transactions
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY transaction_date DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTransactionsRow struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Description     pgtype.Text        `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	Type            string             `json:"type"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.TransactionDate,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET 
    category_id = $2,
    amount = $3,
    description = $4,
    transaction_date = $5,
    type = $6
WHERE id = $1 AND user_id = $7 AND deleted_at IS NULL
RETURNING id, user_id, category_id, amount, description, transaction_date, type
`

type UpdateTransactionParams struct {
	ID              int64              `json:"id"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Description     pgtype.Text        `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	Type            string             `json:"type"`
	UserID          int64              `json:"user_id"`
}

type UpdateTransactionRow struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Description     pgtype.Text        `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	Type            string             `json:"type"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.TransactionDate,
		arg.Type,
		arg.UserID,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.TransactionDate,
		&i.Type,
	)
	return i, err
}
