// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, avatar_url, google_auth_id)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, avatar_url, google_auth_id, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	Name         pgtype.Text `json:"name"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	GoogleAuthID pgtype.Text `json:"google_auth_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.GoogleAuthID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.GoogleAuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, avatar_url, google_auth_id, created_at, updated_at
FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.GoogleAuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, avatar_url, google_auth_id, created_at, updated_at
FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.GoogleAuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleAuthID = `-- name: GetUserByGoogleAuthID :one
SELECT id, email, name, avatar_url, google_auth_id, created_at, updated_at
FROM users WHERE google_auth_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleAuthID(ctx context.Context, googleAuthID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleAuthID, googleAuthID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.GoogleAuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    name = $2, 
    avatar_url = $3
WHERE id = $1
RETURNING id, email, name, avatar_url, google_auth_id, created_at, updated_at
`

type UpdateUserParams struct {
	ID        int64       `json:"id"`
	Name      pgtype.Text `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.GoogleAuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
