apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-3
      auth:
        jwt:
          serviceAccountRef:
            name: catat-api-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catat-api-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: catat-api-secrets
    creationPolicy: Owner
  data:
    
    - secretKey: DB_SOURCE
      remoteRef:
        key: catat  
        property: DB_SOURCE
    
    
    - secretKey: TOKEN_SYMMETRIC_KEY
      remoteRef:
        key: catat
        property: TOKEN_SYMMETRIC_KEY
    
    
    - secretKey: GOOGLE_OAUTH_CLIENT_ID
      remoteRef:
        key: catat
        property: GOOGLE_OAUTH_CLIENT_ID
    
    - secretKey: GOOGLE_OAUTH_CLIENT_SECRET
      remoteRef:
        key: catat
        property: GOOGLE_OAUTH_CLIENT_SECRET
