name: Run Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  issues: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DB_SOURCE: ${{ secrets.DB_SOURCE }}
      SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
      TOKEN_SYMMETRIC_KEY: ${{ secrets.TOKEN_SYMMETRIC_KEY }}
      ACCESS_TOKEN_DURATION: ${{ secrets.ACCESS_TOKEN_DURATION }}
      GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
      GOOGLE_OAUTH_REDIRECT_URL: ${{ secrets.GOOGLE_OAUTH_REDIRECT_URL }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: catat
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5 
        with:
          go-version: "1.24.4"
          cache: true 

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/

      - name: Run migration
        run: make migrateup
      
      - name: Test
        run: make test